### ISSUE TITLE
Just reminders for Brooke :-)

### ISSUE THREAD

**Issue by hrbrmstr** [ropenscilabs/rnoaa#1]
- [x] Acquire [Munchkin](http://www.worldofmunchkin.com/game/)
- [ ] Acquire [Magic the Gathering](http://magic.wizards.com/)
- [ ] Acquire [Tsuro](http://www.calliopegames.com/read/45/tsuro)
- [ ] Acquire [Samurai](http://riograndegames.com/games.html?id=169)
- [ ] Acquire [Pandemic](http://www.zmangames.com/store/p25/Pandemic.html)
- [ ] Acquire [Pandemic Legacy](http://www.zmangames.com/store/p31/Pandemic_Legacy.html)

**Comment by geanders** [comment]
:)

**Comment by geanders** [comment]
In this order?

**Comment by hrbrmstr** [comment]
re-ordered (though if you can play Pandemic at uni it could be pretty fun to do in parallel)
