### ISSUE TITLE
Fix bug in `meteo_coverage` example

### ISSUE THREAD

**Issue by geanders** [ropenscilabs/rnoaa#14]
```
> obs_covr <- meteo_coverage(obs)
Error in function_list[[k]](value) : could not find function "do"
Calls: meteo_coverage ... eval -> _fseq -> freduce -> withVisible -> <Anonymous>
Execution halted
```

**Comment by geanders** [comment]
Now it looks like we're getting this error instead in the example for `meteo_coverage`:

```
> autoplot(obscovr)
Error: could not find function "autoplot"
```

**Comment by masalmon** [comment]
I guess we're lacking the import from ggplot2 for autoplot? That said, I haven't looked at meteo_coverage code properly.

**Comment by masalmon** [comment]
For using autoplot, autoplot needs to be a method, right? Do you want to define a class for meteo_coverage output then? It seems a bit complicated, so maybe we could export the autoplot function... which in turn isn't optimal either.
