### ISSUE TITLE
Data Source: Wavewatch III hindcasts

### ISSUE THREAD

**Issue by jebyrnes** [ropenscilabs/rnoaa#18]
http://polar.ncep.noaa.gov/waves/products.shtml
ftp://polar.ncep.noaa.gov/pub/history/waves/ or ftp://polar.ncep.noaa.gov/pub/waves/

Global hindcasts back to 1997.

**Comment by jebyrnes** [comment]
But grib2 formats - not always fun. Although wgrib2 can convert them to netcdf files.

**Comment by geanders** [comment]
@jebyrnes I think this might be an issue that would be really interesting for the main `rnoaa` GitHub issues page: https://github.com/ropensci/rnoaa/issues Could you move it there?

**Comment by jebyrnes** [comment]
Put it into https://github.com/ropensci/rnoaa/issues/141

**Comment by geanders** [comment]
Thanks!
