### ISSUE TITLE
remove this repo now?

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/rnoaa#36]
@geanders is it okay to delete this repo now? I think you said you moved all changes to your own fork of `ropensci/rnoaa`. If there's still some stuff here you want to preserve before repo removal let me know.

**Comment by geanders** [comment]
Yes, I have moved everything into my own fork, so you can delete the ropenscilabs repo. Thanks for checking!

________________________________

**Comment by sckott** [comment]
thanks!
