### ISSUE TITLE
Consider adding something to track progress

### ISSUE THREAD

**Issue by geanders** [ropenscilabs/rnoaa#5]
If there are a lot of monitors in a county (like in the example), it may take a while to process everything. Some people might be comforted by having the function print out something to show progress while that's processing, so they won't worry that it's stuck. This is probably something to put in the code for meteo_pull_monitors, and then it would show up here.

**Comment by masalmon** [comment]
One could use the utils function txtProgressBar https://stat.ethz.ch/R-manual/R-devel/library/utils/html/txtProgressBar.html

Here is an example https://ryouready.wordpress.com/2009/03/16/r-monitor-function-progress-with-a-progress-bar/

```r 
total <- 20
# create progress bar
pb <- txtProgressBar(min = 0, max = total, style = 3)
for(i in 1:total){
   Sys.sleep(0.1)
   # update progress bar
   setTxtProgressBar(pb, i)
}
close(pb)
```

**Comment by masalmon** [comment]
Or simply to the same as in meteo_coverage with verbose?
