### ISSUE TITLE
problem with `meteo_coverage()` when `verbose = TRUE`

### ISSUE THREAD

**Issue by geanders** [ropenscilabs/rnoaa#7]
My student and I have been getting the error when running `meteo_coverage`:

```
Error in sprintf(" Total number of observations: %s\n\n", comma(nrow(.))) : could not find function "comma"
```

unless we specify that `verbose = FALSE`

**Comment by masalmon** [comment]
comma is a scales function.

**Comment by masalmon** [comment]
I'm fixing this quickly but I also set verbose to FALSE by default, I hope it's ok.
